install:
 - pushd server/node
 - npm install
 - popd

before_script:
 - pushd server/node
 - export RUN_ON_TRAVIS=true
 - npm test
 - popd
 - pushd client/groovy/src/main/resources
 - cp subak.config.sample.json subak.config.json
 - popd

script:
 - pushd server/node
 - npm start &
 - popd
 - pushd client/groovy
 - ./gradlew jar test
 - popd
